baseURL = "https://www.pantrypoints.com/"
title = "Pantrypoints: Points-based Economic System"
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

timeout = "300s"
theme = "hextra"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "RSS" ]


[languages.en]
languageName = "English"
weight = 1
title = "Pantrypoints: Points-based Economic System"

[languages.ar]
languageName = "Arabic"
weight = 2
title = "Pantrypoints: Points-based Economic System"

[languages.zh]
languageName = "简体中"
weight = 3
title = "Pantrypoints: Points-based Economic System"

[languages.fr]
languageName = "French"
weight = 4
title = "Pantrypoints: Points-based Economic System"

#
[languages.de]
languageName = "German"
weight = 5
title = "Pantrypoints: Points-based Economic System"

[languages.id]
languageName = "Indonesian"
weight = 6
title = "Pantrypoints: Points-based Economic System"

[languages.jp]
languageName = "日本語"
weight = 7
title = "Pantrypoints: Points-based Economic System"

[languages.kr]
languageName = "Korean"
weight = 9
title = "Pantrypoints: Points-based Economic System"

#
[languages.es]
languageName = "Spanish"
weight = 10
title = "Pantrypoints"

[languages.tl]
languageName = "Tagalog"
weight = 11
title = "Pantrypoints"


[languages.hi]
languageName = "Hindi"
weight = 12
title = "Pantrypoints"
# [module]
# workspace = "hugo.work"

#   [module.hugoVersion]
#   extended = true
#   min = "0.112.0"

#   [module.imports]
#   path = "github.com/imfing/hextra"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false



[[menu.main]]
identifier = "Trisactions"
name = "/icons/pantry50.png"
weight = 1
url = "/trisactions"

[[menu.main]]
  name = "/icons/banker.png"
  weight = 2
  url = "/trisactions/banking/"

[[menu.main]]
  name = "/icons/energy.png"
  weight = 3
  url = "/trisactions/circle/"

[[menu.main]]
  name = "/icons/place.png"
  weight = 4
  url = "/trisactions/city"

[[menu.main]]
  name = "/icons/banking.png"
  weight = 5
  url = "/trisactions/health/"

# [[menu.main]]
#   name = "/icons/investor.png"
#   weight = 6
#   url = "/trisactions/invesure"

# [[menu.main]]
#   name = "/icons/medal.png"
#   weight = 7
#   url = "/trisactions/nation"

[[menu.main]]
  name = "/icons/w.png"
  weight = 10
  url = "/trisactions/world/"

[[menu.main]]
  name = "/icons/p.png"
  weight = 11
  url = "/pantrypreneur"

[[menu.main]]
  name = "/icons/teacher.png"
  weight = 12
  url = "/pantrypreneur/educate"

[[menu.main]]
  name = "/icons/plants.png"
  weight = 13
  url = "/pantrypreneur/farm"

[[menu.main]]
  name = "/icons/loy.png"
  weight = 16
  url = "/pantrypreneur/rewards"

[[menu.main]]
  name = "/icons/shop.png"
  weight = 18
  url = "/services/build/"

[[menu.main]]
  name = "/icons/cards.png"
  weight = 19
  url = "/services/cards"

[[menu.main]]
  name = "/icons/t.png"
  weight = 24
  url = "/services/tax"

[[menu.main]]
  name = "/icons/decen.png"
  weight = 26
  url = "/services/match"

[[menu.main]]
  name = "/icons/charts.png"
  weight = 28
  url = "/services/pantrylitics/"

[[menu.main]]
  name = "/icons/maps.png"
  weight = 30
  url = "/services/predict/"


[[menu.main]]
weight = 900
name = "/icons/cal.png"
url = "/news"

[[menu.main]]
weight = 903
name = "/icons/faq.jpg"
url = "/faq"

[[menu.main]]
weight = 910
name = "/icons/about.jpg"
url = "/about"


# [[menu.main]]
#   name = "About"
#   weight = 90
#   identifier = "news"

# [[menu.main]]
#   name = "What We Do"
#   weight = 91
#   url = "/company"
#   parent = "news"

# [[menu.main]]
#   name = "News"
#   weight = 92
#   url = "/news/"
#   parent = "news"

# [[menu.main]]
#   name = "FAQ"
#   weight = 93
#   url = "/faq"
#   parent = "news"
  
# [[menu.main]]
#   name = "Docs"
#   weight = 94
#   url = "/docs/intro/overview/"
#   parent = "news"



# [[menu.main]]
#   name = "Supereconomics"
#   weight = 99
#   url = "/company/supereconomics/"
#   parent = "news"


# [[menu.main]]
#   name = "Services"
#   weight = 20
#   identifier = "services"

# [[menu.main]]
#   name = "Build"
#   weight = 40
#   identifier = "build"
#   url = "/build/"
#   parent = "services"

# [[menu.main]]
#   name = "Predict"
#   weight = 41
#   identifier = "predict"
#   url = "/predict/"
#   parent = "services"


# [[footer]]
#   name = "Hub"
#   weight = 50
#   identifier = "hub"
#   url = "mailto:hello@paintrypoints.com"

# [[social]]
#   name = "Facebook"
#   pre = "<svg width='20' viewBox='0 0 448 512' fill='dodgerblue'><path d='M400 32H48A48 48 0 0 0 0 80v352a48 48 0 0 0 48 48h137.25V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.27c-30.81 0-40.42 19.12-40.42 38.73V256h68.78l-11 71.69h-57.78V480H400a48 48 0 0 0 48-48V80a48 48 0 0 0-48-48z'/></svg>"
#   url = "https://facebook.com/pantrypoints"
#   post = "v0.1.0"
#   weight = 10

# [[social]]
#   name = "Youtube"
#   # pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
#   pre = "<svg viewBox='0 0 576 512' width='20' fill='dodgerblue'><path d='M549.655 124.083c-6.281-23.65-24.787-42.276-48.284-48.597C458.781 64 288 64 288 64S117.22 64 74.629 75.486c-23.497 6.322-42.003 24.947-48.284 48.597-11.412 42.867-11.412 132.305-11.412 132.305s0 89.438 11.412 132.305c6.281 23.65 24.787 41.5 48.284 47.821C117.22 448 288 448 288 448s170.78 0 213.371-11.486c23.497-6.321 42.003-24.171 48.284-47.821 11.412-42.867 11.412-132.305 11.412-132.305s0-89.438-11.412-132.305zm-317.51 213.508V175.185l142.739 81.205-142.739 81.201z'/></svg>"
#   url = "https://www.youtube.com/channel/UCn887DnlWjoACK3t1MeSsjQ"
#   weight = 20

# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 512 512' width='20' fill='dodgerblue'><!-- Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) --><path d='M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z'/></svg>"
#   url = "https://twitter.com/pantrypoints"
#   weight = 24



[[menu.main]]
name = "Search"
weight = 99

  [menu.main.params]
  type = "search"



[[menu.sidebar]]
identifier = "more"
name = "More"
weight = 1

  [menu.sidebar.params]
  type = "separator"

[[menu.sidebar]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 2

[[menu.sidebar]]
identifier = "pp"
name = "Pantrypoints ↗"
url = "https://www.pantrypoints.com"
weight = 3

[params]
description = "Modern, responsive, batteries-included Hugo theme for creating beautiful static websites."
displayUpdatedDate = true
dateFormat = "January 2, 2006"

  [params.navbar]
  displayTitle = true
  displayLogo = true
  width = "wide"

    [params.navbar.logo]
    path = "/icons/pantry50.png"
    dark = "/icons/pantry50.png"

  [params.page]
  width = "normal"

  [params.footer]
  displayCopyright = true
  displayPoweredBy = true
  width = "normal"

  [params.search]
  enable = true

  # [params.editURL]
  # enable = true
  # base = "https://github.com/imfing/hextra/edit/main/exampleSite/content"

  [params.comments]
  enable = false
  type = "giscus"

    [params.comments.giscus]
    repo = "imfing/hextra"
    repoId = "R_kgDOJ9fJag"
    category = "General"
    categoryId = "DIC_kwDOJ9fJas4CY7gW"
